import './auth';
import './enterClick';
import './firebaseService';
import './mainController';
import './messageController';
import './utils';
import './voteService';
import './directives/boardContext'
import './directives/dialogs'
import './directives/header'
import './directives/mainContent'
import './directives/mainPage'
import './directives/menu'
import './directives/spinner'
import './services/modalService'
